services:
  app:
    image: ghcr.io/luismarkustorres/cv_automation:${IMAGE_TAG}
    platform: linux/arm64
    container_name: cv-automation
    restart: unless-stopped
    volumes:
      - ./AutomationCVSecret.json:/app/AutomationCVSecret.json:ro
      - ./token.json:/app/token.json
